config/routes.rb
WorkdistributedCom::Application.routes.draw do
  get "listings/start"
  post "listings/preview"
  get "listings/view"
  get "listings/view/:id" => "listings#view"

  post "listings/publish"
  post "listings/publish_prem"

  resources :examples

  get "default/index"

  get "v/:id" => "listings#view"
  get ":slug" => "listings#view"

   root :to => 'default#index'

end

app/models/example.rb
class Example
  include Mongoid::Document
  field :title, type: String
end

app/controllers/examples_controller.rb
class ExamplesController < ApplicationController
  # GET /examples
  # GET /examples.json
  def index
    @examples = Example.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @examples }
    end
  end

  # GET /examples/1
  # GET /examples/1.json
  def show
    @example = Example.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @example }
    end
  end

  # GET /examples/new
  # GET /examples/new.json
  def new
    @example = Example.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @example }
    end
  end

  # GET /examples/1/edit
  def edit
    @example = Example.find(params[:id])
  end

  # POST /examples
  # POST /examples.json
  def create
    @example = Example.new(params[:example])

    respond_to do |format|
      if @example.save
        format.html { redirect_to @example, notice: 'Example was successfully created.' }
        format.json { render json: @example, status: :created, location: @example }
      else
        format.html { render action: "new" }
        format.json { render json: @example.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /examples/1
  # PUT /examples/1.json
  def update
    @example = Example.find(params[:id])

    respond_to do |format|
      if @example.update_attributes(params[:example])
        format.html { redirect_to @example, notice: 'Example was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @example.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /examples/1
  # DELETE /examples/1.json
  def destroy
    @example = Example.find(params[:id])
    @example.destroy

    respond_to do |format|
      format.html { redirect_to examples_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/examples_helper.rb
module ExamplesHelper
end

app/views/examples/_form.html.erb
<%= form_for(@example) do |f| %>
  <% if @example.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@example.errors.count, "error") %> prohibited this example from being saved:</h2>

      <ul>
      <% @example.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/examples/edit.html.erb
<h1>Editing example</h1>

<%= render 'form' %>

<%= link_to 'Show', @example %> |
<%= link_to 'Back', examples_path %>

app/views/examples/index.html.erb
<h1>Listing examples</h1>

<table>
  <tr>
    <th>Title</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @examples.each do |example| %>
  <tr>
    <td><%= example.title %></td>
    <td><%= link_to 'Show', example %></td>
    <td><%= link_to 'Edit', edit_example_path(example) %></td>
    <td><%= link_to 'Destroy', example, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Example', new_example_path %>

app/views/examples/new.html.erb
<h1>New example</h1>

<%= render 'form' %>

<%= link_to 'Back', examples_path %>

app/views/examples/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @example.title %>
</p>


<%= link_to 'Edit', edit_example_path(@example) %> |
<%= link_to 'Back', examples_path %>